services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - api.env
    image: eduardoraider/docker-kubernetes:latest
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379