apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Release.Name }}-redis-svc
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
        - name: redis
          image: "redis:{{ .Values.redis.image_version }}"
          command:
            - "redis-server"
          args:
            - "--requirepass"
            - "$(PASS)"
            - "--appendonly"
            - "yes"
          env:
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis-secret
                  key: REDIS_PASS
          ports:
            - containerPort: {{ .Values.redis.port }}